apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PocSignalRServerless
  description: Poc para teste do uso do Azure SignalR Services no modo Serverless
spec:
  type: website
  lifecycle: experimental
  owner: tie
